name: Bug report
about: Create a report to help us improve

---

name: "Bug report: Запрос в базу данных #10"
body:
- type: markdown
  attributes:
    value: |-
      **Описание проблемы:**
      Запрос к базе данных по ID 10 возвращает ошибку.
- type: input
  id: title
  attributes:
    label: Заголовок
    description: Кратко опишите проблему
    placeholder: Ошибка в запросе по ID 10
    value: Bug report: Запрос в базу данных #10
- type: textarea
  id: body
  attributes:
    label: Подробности
    description: Опишите проблему более подробно
    placeholder: Происходит ошибка при выполнении запроса
- type: dropdown
  id: severity
  attributes:
    label: Степень серьёзности
    description: Выберите степень серьёзности проблемы
    options:
      - Low
      - Medium
      - High

